Repository XatubaPox/poo-ucb-banker, pull requests merged in 2021-09, with the labels that each got.

#1 Feature/class endereco
  .idea/.gitignore
  .idea/compiler.xml
  .idea/gradle.xml
  .idea/jarRepositories.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/modules/projeto-banco/projeto-banco.projeto-banco.test.iml
  .idea/modules/projeto_banco.iml
  .idea/poo-ucb-banker.iml
  .idea/runConfigurations.xml
  .idea/vcs.xml
  poo-projeto-banco/.gradle/7.1/dependencies-accessors/dependencies-accessors.lock
  poo-projeto-banco/.gradle/7.1/dependencies-accessors/gc.properties
  poo-projeto-banco/.gradle/7.1/executionHistory/executionHistory.bin
  poo-projeto-banco/.gradle/7.1/executionHistory/executionHistory.lock
  poo-projeto-banco/.gradle/7.1/fileChanges/last-build.bin
  poo-projeto-banco/.gradle/7.1/fileHashes/fileHashes.bin
  poo-projeto-banco/.gradle/7.1/fileHashes/fileHashes.lock
  poo-projeto-banco/.gradle/7.1/gc.properties
  poo-projeto-banco/.gradle/buildOutputCleanup/buildOutputCleanup.lock
  poo-projeto-banco/.gradle/buildOutputCleanup/cache.properties
  poo-projeto-banco/.gradle/buildOutputCleanup/outputFiles.bin
  poo-projeto-banco/.gradle/checksums/checksums.lock
  poo-projeto-banco/.gradle/vcs-1/gc.properties
  poo-projeto-banco/build.gradle
  poo-projeto-banco/gradle/wrapper/gradle-wrapper.properties
  poo-projeto-banco/gradlew
  poo-projeto-banco/gradlew.bat
  poo-projeto-banco/settings.gradle
  poo-projeto-banco/src/main/java/Endereco.java
Labels: enhancement

#2 fix: update toString() method of the address class
  poo-projeto-banco/src/main/java/Endereco.java
Labels: fix

#5 Feature/class login
  poo-projeto-banco/src/main/java/Main.java
  poo-projeto-banco/src/main/java/model/Login.java
Labels: enhancement, test
