Repository XatubaPox/poo-ucb-banker, pull requests merged in 2021-10, with the labels that each got.

#15 add class agencia
  poo-projeto-banco/src/main/java/model/Agencia.java
Labels: enhancement

#16 feat: add cartao class with incomplete methods.
  poo-projeto-banco/src/main/java/model/Cartao.java
Labels: enhancement

#17 add transacoes class with incomplete update() method.
  poo-projeto-banco/src/main/java/listClasses/Transacoes.java
Labels: enhancement

#18 fix: improving design in ascii.
  poo-projeto-banco/src/main/java/Main.java
  poo-projeto-banco/src/main/java/model/Login.java
Labels: fix

#19 feat: add abstract conta class and its poupanca and corrent child classes with incomplete methods
  poo-projeto-banco/src/main/java/model/Conta.java
  poo-projeto-banco/src/main/java/model/Corrente.java
  poo-projeto-banco/src/main/java/model/Poupanca.java
Labels: enhancement

#20 Fix/some classes
  poo-projeto-banco/src/main/java/model/Agencia.java
  poo-projeto-banco/src/main/java/model/Cartao.java
  poo-projeto-banco/src/main/java/model/Conta.java
  poo-projeto-banco/src/main/java/model/Corrente.java
  poo-projeto-banco/src/main/java/model/Poupanca.java
Labels: enhancement, fix

#21 Feature/class cliente clientes
  poo-projeto-banco/src/main/java/listClasses/Clientes.java
  poo-projeto-banco/src/main/java/model/Cliente.java
Labels: enhancement, fix

#25 feat: implement sacar(), transferir() and depositar() methods in the conta class
  poo-projeto-banco/src/main/java/model/Conta.java
Labels: enhancement

#26 implement depositar() e sacar() methods in the Corrente class.
  poo-projeto-banco/src/main/java/model/Corrente.java
  poo-projeto-banco/src/main/java/model/Poupanca.java
Labels: enhancement, fix

#34 feat: implement withdrawal and deposit in main class.
  poo-projeto-banco/src/main/java/Main.java
  poo-projeto-banco/src/main/java/menu/Menus.java
Labels: enhancement

#35 fix: arrange the mainMenu method according to account type.
  poo-projeto-banco/src/main/java/Main.java
  poo-projeto-banco/src/main/java/model/Conta.java
Labels: fix

#37 feature: generate account number randomly.
  poo-projeto-banco/src/main/java/Main.java
  poo-projeto-banco/src/main/java/model/Cartao.java
  poo-projeto-banco/src/main/java/model/Conta.java
  poo-projeto-banco/src/main/java/model/Corrente.java
  poo-projeto-banco/src/main/java/model/Poupanca.java
Labels: enhancement

#39 feat: create method transferir (incomplete)
  poo-projeto-banco/src/main/java/Main.java
  poo-projeto-banco/src/main/java/listClasses/Transacoes.java
  poo-projeto-banco/src/main/java/model/Cartao.java
  poo-projeto-banco/src/main/java/model/Conta.java
  poo-projeto-banco/src/main/java/model/Corrente.java
  poo-projeto-banco/src/main/java/model/Poupanca.java
  poo-projeto-banco/src/main/java/model/Transacao.java
Labels: enhancement
